const days = [
  ["🌑","Žibintas",["Pirmoji mėnulio diena yra labai trumpa. Ji pasirodo jaunaties tamsoje, kai senasis ciklas jau pasibaigęs, o naujasis dar tik ieško savo formos.","Žibintas simbolizuoja mažą šviesą tamsoje. Ne atsakymus ir ne aiškų kelią, o pirmąjį suvokimą, kuris pasirodo tyliai.","Šią dieną verta prisiminti, kas buvo svarbu praėjusiame cikle. Kokias patirtis pasiimi su savimi? Ką palieki už nugaros?","Kartais užtenka ne naujo plano, o mažos šviesos, kuri padeda pamatyti tai, kas jau seniai buvo šalia.","🌙 Šios dienos raktas – <strong>atpažinimas</strong>."]],
  ["🌑","Gausos kraitė",["Po pirmosios šviesos ateina laikas pažvelgti į tai, ką nešiesi su savimi.","Kraitė simbolizuoja sukauptą patirtį, žinias, talentus ir vertybes. Tai viskas, ką gyvenimas jau sudėjo į tavo rankas, net jei ne visada tai pastebi.","Ši diena kviečia ne ieškoti daugiau, o pamatyti tai, ką jau turi. Kartais didžiausia gausa slypi ne ateities troškimuose, o dabartiniuose turtuose.","Kas šiandien maitina tavo širdį? Ką norėtum pasiimti į naują ciklą?","🌙 Šios dienos raktas – <strong>skalsa</strong>."]],
  ["🌑","Vilkas",["Vilkas simbolizuoja instinktą ir vidinį žinojimą. Tai ta mūsų dalis, kuri dažnai supranta anksčiau, nei spėja paaiškinti protas.","Ši diena kviečia įsiklausyti į tai, ką jau seniai jauti, bet galbūt dar nedrįsai pripažinti. Kartais atsakymas ateina ne per logiką, o per tylų vidinį žinojimą.","Vilkas primena, kad ne viską reikia ieškoti išorėje. Dalis atsakymų jau gyvena tavo atmintyje, patirtyje ir nuojautoje.","Paklausk savęs:","<strong>Kuo šiandien pasitikiu labiau – baime ar savo vidiniu žinojimu?</strong>"]],
  ["🌑","Ąžuolas",["Ąžuolas simbolizuoja šaknis. Tai diena, kai verta prisiminti, iš kur atėjai ir kas tave suformavo.","Kiekvienas žmogus nešasi savo istoriją – šeimos, giminės, vaikystės ir gyvenimo patirtis. Kai kurios jų mus stiprina, kai kurios dar laukia supratimo.","Ši diena kviečia sustoti ir įsiklausyti. Ne į išorinį triukšmą, o į tai, kas giliai įsišakniję tavo viduje.","Paklausk savęs:","<strong>Kokios mano šaknys šiandien suteikia man stiprybės?</strong>"]],
  ["🌑","Devyniaragis",["Devyniaragis užbaigia pirmąjį Raganos laiką. Tai simbolis, kuris primena vidinį stuburą, ištikimybę sau ir tai, ko negalima išduoti einant toliau.","Po atminties, kraitės, instinkto ir šaknų ateina klausimas apie tavo kryptį. Ką iš viso to, ką atpažinai, gali laikyti tikru?","Ši diena kviečia labai atsargiai elgtis su žodžiais, pažadais ir pasirinkimais. Ne viską reikia įtvirtinti garsiai. Kartais pakanka tyliai sau pripažinti, kas yra tavo kelias, o kas jau nebe.","Paklausk savęs:","<strong>Kam šiandien noriu likti ištikima?</strong>"]],
  ["🌒","Gervė",["Gervė atneša pirmąjį lengvumo pojūtį po Raganos laiko. Ji simbolizuoja smalsumą, tyrumą ir gebėjimą pažvelgti į pasaulį naujomis akimis.","Vaikystėje pasaulis atrodo pilnas stebuklų. Debesys tampa gyvūnais, vėjas kalba savo kalba, o kiekviena diena slepia kažką naujo. Gervė primena šį gebėjimą stebėtis.","Ši diena kviečia sustoti ir pastebėti tai, ką kasdienybėje dažnai praleidžiame. Kartais svarbiausi atradimai ateina ne per pastangas, o per dėmesį.","Paklausk savęs:","<strong>Kas šiandien pažadina mano smalsumą?</strong>"]],
  ["🌒","Gaidys",["Gaidys simbolizuoja balsą. Tai diena, kai mokomės išsakyti save ir atrasti savo vietą tarp kitų.","Vaikystėje ateina momentas, kai nebeužtenka tik stebėti pasaulį. Norisi kalbėti, klausti, pasakoti, būti išgirstai. Gaidys primena šią pirmąją drąsą parodyti save.","Žodžiai turi galią. Jie gali padrąsinti, suartinti, padėti suprasti. Jie taip pat gali žeisti. Ši diena kviečia atkreipti dėmesį ne tik į tai, ką sakome, bet ir kaip klausomės.","Paklausk savęs:","<strong>Ką šiandien noriu pasakyti pasauliui?</strong>"]],
  ["🌒","Ryto žarija",["Ryto žarija simbolizuoja pirmąją vidinę kibirkštį. Dar ne liepsną, ne didelį laužą, o mažą šilumą, iš kurios gali gimti kažkas daugiau.","Kaip seniau rytą iš vakarykštės žarijos būdavo įkuriama nauja ugnis, taip ir ši diena primena, kad svarbiausi dalykai dažnai prasideda nuo mažų ženklų, minčių ar troškimų.","Aušrinės laikas moko pastebėti tai, kas bunda. Ne skubinti, ne versti augti, o leisti tam tyliai rusenti ir stiprėti.","Paklausk savęs:","<strong>Kas šiandien manyje rusena?</strong>"]],
  ["🌒","Šikšnosparnis",["Šikšnosparnis simbolizuoja gebėjimą matyti tai, kas nematoma iš pirmo žvilgsnio. Tai diena, kai verta neskubėti daryti išvadų ir nepasitikėti vien tuo, kas matoma paviršiuje.","Kartais pasaulis atrodo aiškus, tačiau tikrovė būna sudėtingesnė. Ši diena primena, kad ne viskas yra taip, kaip atrodo iš pirmo žvilgsnio.","Kaip šikšnosparnis orientuojasi tamsoje pasikliaudamas savo pojūčiais, taip ir mes galime atrasti kryptį klausydamiesi vidinio balso, o ne vien išorinių nuomonių.","Paklausk savęs:","<strong>Kur šiandien matau tik paviršių, o kur slypi gilesnė tiesa?</strong>"]],
  ["🌒","Šaltinis",["Šaltinis simbolizuoja gyvybę, kuri teka natūraliai. Tai diena, kai nereikia nieko stumti ar skubinti. Pakanka leisti gyvenimui tekėti savo vaga.","Po šešėlių, klausimų ir ieškojimų ateina lengvesnis kvėpavimas. Kaip šaltinio vanduo randa kelią per žemę, taip ir mūsų vidinis pasaulis kartais pats žino, kur judėti.","Ši diena primena, kad stiprybė nebūtinai gimsta iš pastangų. Kartais ji gimsta iš pasitikėjimo.","Paklausk savęs:","<strong>Kas šiandien mane maitina ir stiprina?</strong>"]],
  ["🌒","Rūtų vainikas",["Rūtų vainikas simbolizuoja perėjimą iš vaikystės į jaunystę. Tai diena, kai pradedame aiškiau matyti save ir savo vietą pasaulyje.","Vaikystė moko pažinti pasaulį. Rūtų vainikas primena, kad ateina laikas pažinti ir save.","Tai ne išorinis pasikeitimas, o vidinis suvokimas. Kaip iš žalių rūtų pinamas vainikas, taip ir žmogaus tapatybė pamažu pinasi iš patirčių, svajonių ir pasirinkimų.","Paklausk savęs:","<strong>Kas manyje šiandien skleidžiasi?</strong>"]],
  ["🌕","Taurė",["Taurė simbolizuoja širdies talpą. Tai diena, kai mokomės priimti jausmus jų neišpilant ir neužspaudžiant.","Jaunystėje širdis pradeda atsiverti stipriau. Atsiranda pirmi gilūs jausmai, prisirišimai, ilgesys, jautrumas kitam žmogui ir sau pačiai.","Taurė primena, kad jautrumas nėra silpnumas. Tai gebėjimas laikyti tai, kas svarbu, net tada, kai viduje daug vandens.","Paklausk savęs:","<strong>Ką šiandien noriu priimti į savo širdį?</strong>"]],
  ["🌕","Verpstė",["Verpstė simbolizuoja gyvenimo siūlą, kuris kuriamas ne vienu dideliu sprendimu, o daugybe mažų pasirinkimų.","Kartais atrodo, kad gyvenime vis sugrįžtame prie tų pačių situacijų. Tačiau kiekvienas sugrįžimas suteikia galimybę pamatyti save naujai ir pasirinkti kitaip.","Jaunystė moko ne tik svajoti, bet ir kurti. Kaip verpstėje plonas pluoštas virsta siūlu, taip ir mūsų patirtys pamažu tampa gyvenimo audiniu.","Paklausk savęs:","<strong>Kokį siūlą šiandien verpiu savo gyvenime?</strong>"]],
  ["🌕","Birbynė",["Birbynė simbolizuoja kvietimą ir kryptį. Tai garsas, kuris ne įsako, o pažadina vidinį aiškumą.","Jaunystėje ateina momentas, kai nebeužtenka tik svajoti ar ruoštis. Norisi išgirsti savo kelią ir išdrįsti jam atsiliepti.","Birbynė primena, kad tikras kvietimas dažnai skamba paprastai. Jis gali ateiti kaip noras pradėti, pasakyti, kurti, išeiti į savo lauką.","Paklausk savęs:","<strong>Koks kvietimas šiandien manyje skamba?</strong>"]],
  ["🌕","Gyvatė",["Gyvatė simbolizuoja instinktą, pagundą ir vidinę jėgą. Tai diena, kai aiškiau pajuntame, kas mus traukia, erzina, vilioja ar išveda iš pusiausvyros.","Jaunystėje ateina laikas susidurti su savo galia. Ne tik gražia, šviesia, patogia. Ir su ta, kuri kyla iš kūno, pykčio, noro, pavydo ar aistros.","Gyvatė primena, kad instinktas nėra priešas. Svarbiausia išmokti jį atpažinti ir laikyti sąmoningai, kad jis nevirstų aklu veiksmu.","Paklausk savęs:","<strong>Kokia jėga šiandien manyje prašo būti pamatyta?</strong>"]],
  ["🌕","Gulbė",["Gulbė simbolizuoja vidinę darną. Tai diena, kai po ieškojimų, klausimų ir augimo galima aiškiau pamatyti, kas iš tiesų svarbu.","Jaunystė moko ne tik atrasti save, bet ir priimti save tokią, kokia esi. Su savo stiprybėmis, jautrumu, svajonėmis ir pasirinkimais.","Gulbė primena, kad tikras grožis gimsta iš vientisumo. Kai vidus ir išorė nebekovoja tarpusavyje, atsiranda ramybė.","Paklausk savęs:","<strong>Kas šiandien man padeda jaustis savimi?</strong>"]],
  ["🌕","Javų pėdas",["Javų pėdas simbolizuoja pirmąjį derlių. Tai diena, kai galime pamatyti, kas jau užaugo iš mūsų patirčių, pasirinkimų ir kasdienio darbo.","Austėjos laiko pabaigoje ateina suvokimas, kad tai, ką auginame savyje, anksčiau ar vėliau tampa dovana pasauliui.","Javų pėdas primena, kad branda nėra tik asmeninis pasiekimas. Tai ir gebėjimas dalintis tuo, kas jau subrendo.","Paklausk savęs:","<strong>Kuo šiandien galiu dalintis su pasauliu?</strong>"]],
  ["🌖","Šulinys",["Šulinys simbolizuoja žvilgsnį į gylį. Tai diena, kai verta sustoti ir pažvelgti ne į paviršių, o į tai, kas slypi po juo.","Medeinos laike prasideda brandesnis santykis su savimi. Čia nebeužtenka matyti tik tai, kas akivaizdu. Reikia drąsos nusileisti giliau ir pamatyti, kas iš tiesų kartojasi tavo gyvenime.","Šulinys primena, kad atsakymai ne visada ateina iš išorės. Kartais juos randame tik tada, kai liaujamės blaškytis ir leidžiame sau pamatyti savo pačios atspindį gilumoje.","Paklausk savęs:","<strong>Ką šiandien manyje atspindi mano gyvenimas?</strong>"]],
  ["🌖","Laumė",["Laumė simbolizuoja tai, kas vilioja nuklysti nuo savo kelio. Tai diena, kai verta atidžiau stebėti ne kitus, o save.","Kartais didžiausi spąstai slypi ne pasaulyje, o mūsų pačių mintyse. Abejonės, senos nuoskaudos, svetimi lūkesčiai ar noras įtikti gali nuvesti ten, kur iš tiesų nenorime eiti.","Medeinos laikas moko atpažinti ne tik savo stiprybę, bet ir tai, kas trukdo ja pasitikėti.","Paklausk savęs:","<strong>Kas šiandien mane vilioja nusisukti nuo savo kelio?</strong>"]],
  ["🌖","Erelis",["Erelis simbolizuoja platų žvilgsnį ir gebėjimą matyti daugiau nei šią akimirką.","Kartais gyvenime įstringame smulkmenose, rūpesčiuose ar kasdieniuose sprendimuose. Erelis kviečia pakilti aukščiau ir pažvelgti į savo kelią iš didesnės perspektyvos.","Medeinos laike tai diena, kai verta prisiminti, kur eini ir dėl ko eini. Ne kiekvienas žingsnis svarbus pats savaime, tačiau visi kartu jie kuria kryptį.","Paklausk savęs:","<strong>Ką šiandien matau iš aukščiau, ko nepastebiu būdama per arti?</strong>"]],
  ["🌖","Avilys",["Avilys simbolizuoja bendrystę, bendrą darbą ir vietos atradimą tarp kitų.","Ne viską gyvenime sukuriame vienos. Kartais svarbiausi dalykai gimsta bendradarbiaujant, dalinantis patirtimi ir prisidedant prie bendro tikslo.","Medeinos laike tai diena, kai verta prisiminti, kad stiprybė slypi ne tik savarankiškume, bet ir gebėjime veikti kartu.","Paklausk savęs:","<strong>Prie kokio bendro kūrinio šiandien prisidedu?</strong>"]],
  ["🌖","Raktas",["Raktas simbolizuoja supratimą, kuris ateina tada, kai neskubame. Tai diena, kai viena mintis, sakinys ar seniai pastebėta detalė gali atverti daugiau, nei tikėjomės.","Medeinos laike tai metas sustoti ir peržiūrėti, kokios durys dabar yra prieš tave. Ne visas reikia atidaryti iš karto. Kai kurios laukia brandesnio žvilgsnio.","Raktas primena, kad atsakymai dažnai slypi ne dideliuose ženkluose, o tame, kas tyliai kartojasi mūsų gyvenime.","Paklausk savęs:","<strong>Kokios durys šiandien prašo mano dėmesio?</strong>"]],
  ["🌖","Medžioklės ragas",["Medžioklės ragas simbolizuoja susitelkimą, tikslą ir pasiruošimą veikti. Tai diena, kai viduje gali pasigirsti aiškus kvietimas: laikas nukreipti savo jėgą.","Medeinos laike ši diena kalba apie brandų veiksmą. Ne apie puolimą, ne apie skubėjimą, o apie gebėjimą žinoti, ko sieki, ir eiti ta kryptimi.","Medžioklės ragas primena, kad tikslas reikalauja ne tik noro, bet ir atsakomybės. Kai išgirsti kvietimą, svarbu veikti sąmoningai.","Paklausk savęs:","<strong>Kur šiandien nukreipiu savo jėgą?</strong>"]],
  ["🌖","Meška",["Meška simbolizuoja vidinę jėgą, atramą ir gebėjimą pasirūpinti tuo, kas svarbu. Tai diena, kai stiprybė atsiskleidžia per ramybę, o ne per kovą.","Medeinos laiko pabaigoje ateina suvokimas, kad tikra galia slypi ne tik veikime, bet ir gebėjime išlaikyti. Save, savo žmones, savo vertybes ir tai, ką užauginai.","Meška primena, kad branda nėra triukšminga. Ji rami, kantri ir pasitikinti savo vieta pasaulyje.","Paklausk savęs:","<strong>Kur šiandien jaučiu savo tikrąją atramą?</strong>"]],
  ["🌘","Gilė",["Gilė simbolizuoja sukauptą išmintį ir tai, kas lieka po visų gyvenimo sezonų. Mažoje gilėje slypi visas būsimas ąžuolas.","Velionos laike ši diena kviečia atsigręžti į tai, ką jau sukaupei. Patirtis, žinios, prisiminimai ir išgyventos istorijos tampa vidiniu lobynu.","Gilė primena, kad ne viskas turi augti iš karto. Kai kuriems dalykams reikia laiko subręsti ir surasti savo žemę.","Paklausk savęs:","<strong>Kokią sėklą šiandien nešuosi ateičiai?</strong>"]],
  ["🌘","Pelkė",["Pelkė simbolizuoja klampumą, iliuzijas ir vietas, kuriose lengva pasiklysti, jei skubame.","Velionos laike ši diena kviečia sulėtėti ir atsargiau žiūrėti į tai, kas atrodo aišku. Ne viskas, kas gražiai skamba, veda ten, kur iš tiesų nori eiti.","Pelkė primena, kad kartais geriausias veiksmas yra sustoti. Palaukti, kol nusės vidinė migla, ir tik tada spręsti, kas tikra, o kas tik laikinas vaizdinys.","Paklausk savęs:","<strong>Kur šiandien galiu įklimpti, jei skubėsiu?</strong>"]],
  ["🌘","Nendrė",["Nendrė simbolizuoja lankstumą, tylą ir gebėjimą išlikti savimi net tada, kai aplink keičiasi vėjai.","Velionos laike ši diena kviečia ne priešintis, o įsiklausyti. Kartais išmintis ateina ne per stiprumą, o per gebėjimą nusileisti, prisitaikyti ir išlaukti.","Nendrė primena, kad lankstumas nėra silpnumas. Tai brandi jėga, kuri leidžia nesulūžti ten, kur kietumas tik trukdytų.","Paklausk savęs:","<strong>Kur šiandien galiu būti lankstesnė, neprarasdama savęs?</strong>"]],
  ["🌘","Vandens lelija",["Vandens lelija simbolizuoja ramybę, vidinį skaidrumą ir gebėjimą išlikti šviesiai net giliuose vandenyse.","Velionos laike ši diena kviečia sustoti ir pajusti tai, kas jau subrendo. Nebereikia skubėti, įrodinėti ar ieškoti. Kartais atsakymas ateina tada, kai nustojame jo vaikytis.","Vandens lelija primena, kad tikra ramybė nėra tuštuma. Tai būsena, kurioje galime aiškiau matyti save, savo kelią ir tai, kas iš tiesų svarbu.","Paklausk savęs:","<strong>Ką šiandien galiu priimti su ramybe?</strong>"]],
  ["🌘","Pelenai",["Pelenai simbolizuoja tai, kas jau atliko savo paskirtį. Tai diena paleisti tai, kas baigėsi, ir nebesinešti to į naują ciklą.","Prieš pat jaunatį gyvenimas kviečia sustoti ir peržiūrėti, ko daugiau nebereikia. Senos mintys, įpročiai, nuoskaudos ar neištesėti lūkesčiai gali būti paleisti kaip ugnyje sudegęs medis.","Pelenai primena, kad pabaiga nėra praradimas. Ji sukuria vietos tam, kas netrukus gims iš naujo.","Paklausk savęs:","<strong>Ką šiandien esu pasiruošusi paleisti?</strong>"]],
  ["🌘","Rauda",["Rauda simbolizuoja atsisveikinimą, paleidimą ir pagarbą nueitam keliui. Tai paskutinė mėnulio ciklo diena, kai verta sustoti ir padėkoti už viską, ką šis laikas atnešė.","Velionos laike ši diena primena, kad kiekviena pabaiga turi savo grožį. Tik paleidę tai, kas jau atliko savo paskirtį, galime atverti vietos naujai pradžiai.","Rauda nėra liūdesys. Tai širdies gebėjimas pagerbti tai, kas buvo svarbu, ir išlydėti tai su dėkingumu.","Paklausk savęs:","<strong>Su kuo šiandien atsisveikinu dėkinga širdimi?</strong>"]]
];

const goddessGroups = [
  [5, "Ragana", "https://i.postimg.cc/G9zdsnL4/Ragana-st.png"],
  [11, "Aušrinė", "https://i.postimg.cc/zy8vYFGL/Ausrine-st.png"],
  [17, "Austėja", "https://i.postimg.cc/S2BQTWP8/Austeja-st.png"],
  [23, "Medeina", "https://i.postimg.cc/21kkKj07/Medeina-st.png"],
  [30, "Veliona", "https://i.postimg.cc/rR2cCqdS/Veliona-st.png"]
];

const referenceNewMoon = Date.parse("2026-07-14T09:43:00Z");
const synodicMonthDays = 29.530588853;
const elapsedDays = (Date.now() - referenceNewMoon) / 86400000;
const moonAge = ((elapsedDays % synodicMonthDays) + synodicMonthDays) % synodicMonthDays;
const currentIndex = Math.min(29, Math.floor(moonAge));

const grid = document.querySelector("#day-grid");
const reading = document.querySelector("#reading");

days.forEach((day, index) => {
  const button = document.createElement("button");
  button.type = "button";
  button.className = `day-button${index === currentIndex ? " current" : ""}`;
  button.setAttribute("aria-label", `${index + 1} mėnulio diena – ${day[1]}`);
  button.innerHTML = `<span class="phase">${day[0]}</span><span class="number">${index + 1}</span>`;
  button.addEventListener("click", () => openDay(index));
  grid.append(button);
});

function openDay(index, updateHash = true) {
  const day = days[index];
  document.querySelector("#reading-day").textContent = `${day[0]} ${index + 1} mėnulio diena`;
  document.querySelector("#reading-title").textContent = day[1];
  document.querySelector("#reading-body").innerHTML = day[2].map(text => `<p>${text}</p>`).join("");
  reading.classList.add("open");
  if (updateHash) history.replaceState(null, "", `#diena-${index + 1}`);
  reading.focus({ preventScroll: true });
  reading.scrollIntoView({ behavior: "smooth", block: "start" });
}

function closeDay() {
  reading.classList.remove("open");
  history.replaceState(null, "", location.pathname + location.search);
}

const today = days[currentIndex];
document.querySelector("#moon-number").textContent = currentIndex + 1;
document.querySelector("#today-title").textContent = today[1];
const goddess = goddessGroups.find(group => currentIndex < group[0]);
document.querySelector("#goddess-name").textContent = goddess[1];
document.querySelector("#goddess-image").src = goddess[2];
document.querySelector("#goddess-image").alt = goddess[1];
document.querySelector("#open-today").addEventListener("click", () => openDay(currentIndex));
document.querySelector("#close-reading").addEventListener("click", closeDay);

const requestedDay = Number(location.hash.match(/^#diena-(\d{1,2})$/)?.[1]);
if (requestedDay >= 1 && requestedDay <= 30) openDay(requestedDay - 1, false);
